import { cn } from "@/lib/utils";

export function formatBudgetMoney(amount: number) { return `¥${amount.toLocaleString("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export function BudgetOverview({ totalBudget, planned, remainingToAllocate, actualSpend }: { totalBudget: number; planned: number; remainingToAllocate: number; actualSpend: number }) {
  const overAllocated = remainingToAllocate < 0;
  return <section className="overflow-hidden rounded-lg border border-border bg-surface-1"><div className="grid sm:grid-cols-2 xl:grid-cols-4"><Metric label="项目总预算" value={formatBudgetMoney(totalBudget)} detail="已确认的项目预算池" /><Metric label="已编排" value={formatBudgetMoney(planned)} detail="预算项规划合计" bordered /><Metric label="剩余可分配" value={formatBudgetMoney(remainingToAllocate)} detail={overAllocated ? "已超出项目预算池" : "可继续编排"} danger={overAllocated} bordered /><Metric label="实际支出" value={formatBudgetMoney(actualSpend)} detail="已扣除退款后的净额" bordered /></div><div className="grid gap-4 border-t border-border px-4 py-3 sm:grid-cols-2"><ProgressLine label="预算编排" value={planned} total={totalBudget} tone="primary" /><ProgressLine label="实际支出" value={actualSpend} total={totalBudget} tone="success" /></div></section>;
}

function Metric({ label, value, detail, danger = false, bordered = false }: { label: string; value: string; detail: string; danger?: boolean; bordered?: boolean }) { return <div className={cn("px-4 py-3.5", bordered && "border-t border-border sm:border-l sm:border-t-0")}><p className="text-xs text-muted-foreground">{label}</p><p className={cn("mt-1 font-mono text-lg font-semibold tabular-nums", danger && "text-destructive")}>{value}</p><p className={cn("mt-1 text-[11px]", danger ? "text-destructive" : "text-muted-foreground")}>{detail}</p></div>; }
function ProgressLine({ label, value, total, tone }: { label: string; value: number; total: number; tone: "primary" | "success" }) { const percent = total > 0 ? Math.min((value / total) * 100, 100) : 0; return <div><div className="flex items-center justify-between text-xs"><span className="text-muted-foreground">{label}</span><span className="font-mono tabular-nums">{Math.round(percent)}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-secondary"><div className={cn("h-full rounded-full", tone === "primary" ? "bg-primary" : "bg-success")} style={{ width: `${percent}%` }} /></div></div>; }
